// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CostSince(start: string, platform: string): $CancellablePromise<number> {
    return $Call.ByID(445919367, start, platform);
}

export function ListProviders(platform: string): $CancellablePromise<string[]> {
    return $Call.ByID(790916236, platform).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListRequestLogs(platform: string, provider: string, limit: number): $CancellablePromise<$models.ReqeustLog[]> {
    return $Call.ByID(1199056012, platform, provider, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ProviderDailyStats(platform: string): $CancellablePromise<$models.ProviderDailyStat[]> {
    return $Call.ByID(974013659, platform).then(($result: any) => {
        return $$createType4($result);
    });
}

export function StatsSince(platform: string): $CancellablePromise<$models.LogStats> {
    return $Call.ByID(2831143405, platform).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.ReqeustLog.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.ProviderDailyStat.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.LogStats.createFrom;
