// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetworkService 网络配置服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetNetworkSettings 获取网络设置
 */
export function GetNetworkSettings(): $CancellablePromise<$models.NetworkSettings> {
    return $Call.ByID(716731921).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveNetworkSettings 保存网络设置
 */
export function SaveNetworkSettings(settings: $models.NetworkSettings): $CancellablePromise<void> {
    return $Call.ByID(624586330, settings);
}

// Private type creation functions
const $$createType0 = $models.NetworkSettings.createFrom;
