// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 管理全局配置
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetIntSetting 获取整数类型的配置值（通用方法）
 * 如果找不到或解析失败，返回 0
 */
export function GetIntSetting(key: string): $CancellablePromise<number> {
    return $Call.ByID(900230874, key);
}

/**
 * SetIntSetting 设置整数类型的配置值（通用方法）
 */
export function SetIntSetting(key: string, value: number): $CancellablePromise<void> {
    return $Call.ByID(1050634246, key, value);
}
